/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://ito2-ci.bmwgroup.net/nexus/repository/mdbpipe-releases/")
    }

    maven {
        url = uri("https://ito2-ci.bmwgroup.net/nexus/repository/mdbpipe-snapshots/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-data-jpa:3.0.0")
    api("org.springframework.boot:spring-boot-starter-security:3.0.0")
    api("org.springframework.boot:spring-boot-starter-validation:3.0.0")
    api("org.springframework.boot:spring-boot-starter-web:3.0.0")
    api("org.projectlombok:lombok:1.18.24")
    api("com.auth0:java-jwt:4.0.0")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:3.0.0")
    runtimeOnly("org.postgresql:postgresql:42.5.1")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.0.0")
    testImplementation("org.springframework.security:spring-security-test:6.0.0")
}

group = "com.quan"
version = "0.0.1-SNAPSHOT"
description = "course-peer-review"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
